apiVersion: v1
kind: Pod
metadata:
  name: generate-log-volume
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh","-c"]
    args: [" date  >> /opt/date.log;"]
    volumeMounts:
    - mountPath : /opt
      name: data-volume
  volumes:
  - name: data-volume
    hostPath:
       path: /home/opc/app-data
       type: Directory
