apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mybusybox
  name: mybusybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mybusybox
  template:
    metadata:
      labels:
        app: mybusybox
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - mkdir /vol; date >> /vol/date.log ; cat /vol/date.log; sleep 3600;
        image: busybox
        name: busybox
