apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-busybox
  name: my-busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-busybox
  template:
    metadata:
      labels:
        app: my-busybox
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - while true; do echo hello > /hello.txt ; cat /hello.txt; sleep 10;done
        image: busybox
        name: busybox
