apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-busybox
  name: my-busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-busybox
  template:
    metadata:
      labels:
        app: my-busybox
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - mkdir /vol;  echo 'hello world' > /vol/hello.txt ; cat /vol/hello.txt; sleep 10;
        image: busybox
        name: busybox
